# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ✅ React Native Maps (Google provider)
rn_maps_path = '../node_modules/react-native-maps'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'periscope_clone' do
  config = use_native_modules!

  # ✅ Google Maps pods
  # react-native-maps/Google çoğu zaman GoogleMaps'i zaten çeker ama
  # AppDelegate.swift'te `import GoogleMaps` kullandığın için bunu da eklemek stabil olur.
  pod 'react-native-maps/Google', :path => rn_maps_path
  pod 'GoogleMaps'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true
    )
  end
end
